### ISSUE TITLE
input in "<description>" area is buggy

### ISSUE THREAD

**Issue by TakahiroHaruyama** [pidydx/PyIOCe#2] opened 2015-03-02 05:25 UTC
I tried to input text into description area, but I couldn't. Every time I input a character, the cursor moves to the left. Could you check it on Windows?

**Comment by pidydx** [comment] 2015-03-05 21:27
I tested this on Windows and the description area seems to be working with release-0.9.7.  Is this something that happens any time you use it or are there specific situations where it starts doing this?

**Comment by TakahiroHaruyama** [comment] 2015-03-06 05:52
Type Enter in the description area. After that, the cursor becomes buggy. I used the same version.

**Comment by pidydx** [comment] 2015-03-06 06:01
The multiline box under the Author right?  Was this an IOC created with PyIOCe or is it consistent any time you try?  I am still unable to reproduce. :(

**Comment by TakahiroHaruyama** [comment] 2015-03-06 06:10
Yes, I can always reproduce it.
For example, I'd like to write like following:
hoge
fuga

But, practically, the result is like attached image.
![buggy_desc](https://cloud.githubusercontent.com/assets/6092487/6520979/9a6d15ee-c412-11e4-8124-11b8a9fafd57.png)
After typing Enter, the cursor always moves to far left every time I input a character.

**Comment by pidydx** [comment] 2015-03-06 17:30
Wow, that is weird.  I was able to reproduce it with an IOC open.  The text box behaves normally if an IOC isn't open. If you actually arrow down and delete the newline then the behavior reverts to normal.  That box will wordwrap appropriately if you don't use Enter.  This is also a Windows only issue so it is probably due to the way the windows handles newline stuff when writing to the XML.

**Comment by pidydx** [comment] 2015-03-06 20:41
This has been fixed in this repo.  I will work on getting a new fully packaged client published soon.

**Closed as completed by pidydx** 2015-03-06 20:41 UTC

**Comment by TakahiroHaruyama** [comment] 2015-03-09 05:40
I also checked the bug was fixed. Thank you so much!

**Comment by pidydx** [comment] 2015-03-09 20:17
I just pushed the packaged version to the yahoo/PyIOCe repo
